"""added tables sales_data llmanalisis

Revision ID: aafbeafa80b9
Revises: 000000000000
Create Date: 2024-11-12 19:57:51.505734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aafbeafa80b9'
down_revision: Union[str, None] = '000000000000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_analysis_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_analysis_result_id'), 'llm_analysis_result', ['id'], unique=False)
    op.create_table('sales_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_data_id'), 'sales_data', ['id'], unique=False)
    op.create_index(op.f('ix_sales_data_product_id'), 'sales_data', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_data_product_id'), table_name='sales_data')
    op.drop_index(op.f('ix_sales_data_id'), table_name='sales_data')
    op.drop_table('sales_data')
    op.drop_index(op.f('ix_llm_analysis_result_id'), table_name='llm_analysis_result')
    op.drop_table('llm_analysis_result')
    # ### end Alembic commands ###
